include: package:flutter_lints/flutter.yaml

analyzer:
  # Generated localization files are not linted.
  exclude:
    - lib/src/l10n/app_localizations*.dart
    - build/**
    - android/**

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_fields: true
